### ISSUE TITLE
addCustomField with multiselect not working

### ISSUE THREAD

**Issue by namig** [dotzero/amocrm-php#1]
В коде не нашел каким образом добавляются поля типа мультиселект

**Comment by dotzero** [comment]
Спасибо, что-то я упустил этот момент. Теперь добавил новый метод.

```php
$contact = $amo->contact;
$contact->addCustomMultiField(426106, [
    1237755,
    1237757
]);
```

**Comment by namig** [comment]
Тоже добавлял такой метод.
Сейчас обновлюсь.
Очень полезная библиотека, спасибо.
