### ISSUE TITLE
Не хватает раздела customers

### ISSUE THREAD

**Issue by alexk984** [dotzero/amocrm-php#10]
https://developers.amocrm.ru/rest_api/customers/set.php если не будете делать, то я сам сделаю pull request.

**Comment by sstepanovvl** [comment]
Делай, не стесняйся!

**Comment by dotzero** [comment]
Планирую, но пока руки не дошли. Так как сражу же надо делать и https://developers.amocrm.ru/rest_api/customers_periods/list.php

**Comment by dotzero** [comment]
Добавил две новые модели `Customer` и `CustomersPeriods`.
