### ISSUE TITLE
Узнать ID поля

### ISSUE THREAD

**Issue by Aligan** [dotzero/amocrm-php#15]
Из вашего примера:
```
$contact->addCustomField(448, [
        ['+79261112233', 'WORK'],
    ]);
```
Как вы узнаете ID поля, в данном примере  — **448**

**Comment by dotzero** [comment]
ID всех кастомных полей можно узнать воспользовавшись методом `$amo->account->apiCurrent()`, как указано в примере https://github.com/dotzero/amocrm-php/blob/master/examples/account.php

**Comment by Aligan** [comment]
Спасибо!
