### ISSUE TITLE
Может не сработать $modified = 'now'

### ISSUE THREAD

**Issue by KingComp** [dotzero/amocrm-php#18]
_При update полей столкнулся с тем, что если скрипт сработает быстро, то текущий timestamp будет равен last_modified и сервер вернет ошибку._

**А именно:** 
WebHook вызывал PHP-скрипт, который добавлял ID сделки в кастомное поле. Скрипт отрабатывал случайно (то получалось, то нет).

Если сравнивать last_modified от сервера при вызове с WebHook и time(), получим разницу в 1 секунду. 

**Пример:**
Разница между секундами 1000 мсек.
То есть, если пришел ответ с сервера на 900 мсек (девятисотой миллисекунде), то спустя 100 мсек разница будет в секунду для значения time().
А если ответ с сервера пришел на 0 мсек, то у нас есть 1000 мсек, чтобы получить time() = last_modified.

Здесь уже срабатывает теория вероятности на получение ошибки.

По идеи на стороне AmoCRM надо сделать допуск на то, что last_modified может быть равной для update и все. Но пока они этого не сделали.

**Решение:**
Добавлять 1 секунду: last_modified = strtotime('+1 seconds')

Но это частный случай, который может породить другие проблемы (хоть и маловероятные).

**Comment by KingComp** [comment]
Или просто задать sleep(1000)

**Comment by dotzero** [comment]
Тут нет общего решения. Только если при ловле вебхука сделать sleep на одну секунду перед выполнением update.
