### ISSUE TITLE
$amo->links   Error (104): Запрашиваемый метод API не найден

### ISSUE THREAD

**Issue by recomp** [dotzero/amocrm-php#19]
Error (104): Запрашиваемый метод API не найден
пробовал подставить код из примера, с моими данными - выдает ошибку..

**Comment by dotzero** [comment]
А можно целом пример кода, потому что `$amo->links` просто возвращает экземпляр `AmoCRM\Models\Links`, а дальше какой из методов вы использовали и с какими параметрами?

**Comment by recomp** [comment]
$link = $amo->links;
    $link['from'] = 'leads';
    $link['from_id'] = *******;
    $link['to'] = 'contacts';
    $link['to_id'] = *****;
    var_dump($link->apiLink());

Все из вашего кода [examples](https://github.com/dotzero/amocrm-php/blob/master/examples/links.php), только id мои..

**Comment by dotzero** [comment]
Попробуйте включить режим отладки:

```php
$link = $amo->links;
$link->debug(true); // режим отладки
$link['from'] = 'leads';
$link['from_id'] = 100;
$link['to'] = 'contacts';
$link['to_id'] = 200;
var_dump($link->apiLink());
```

В ответе можно посмотреть куда конкретно он пытался посылать запросы и что ответил сервер AmoCrm:

```
[DEBUG] url: https://example.amocrm.ru/private/api/v2/json/links/set...
[DEBUG] post params: {"request":{"links":{"link":[{"from":"leads","from_id":100,"to":"contacts","to_id":200}]}}}
[DEBUG] curl_exec: {"response":{"links":{"link":{"links":[],"errors":[{"id":0,"code":403,"message":"Error 288.","request_id":0}]}},"server_time":1490420521}}
```
