### ISSUE TITLE
Tags for Leads are not added

### ISSUE THREAD

**Issue by temposys** [dotzero/amocrm-php#2]
Добрый день 
Пытаюсь добавить теги к сделке - не присваиваются, сделка создается успешно, без ошибок, но в амосрм теги не попадают. 
Тоже самое для контакта - работает без проблем. Теги есть.

Код для сделки:

```
$amo          = new AmoCRM($config->amo_host, $config->amo_email, $config->amo_api);
$lead         = $amo->lead;
$lead['name'] = $config->lead_title;
$lead['status_id'] = $config->status_id;
$lead['responsible_user_id'] = $config->responsible_user_id;
$lead['tags'] = 'САЙТ';
$newLead = $lead->apiAdd();
```
Что я делаю не так? Ошибки нет и тега нет.

Когда в теге передавала имя домена была ошибка :

`Error (0): Код ошибки 205. В случае повторного возникновения ошибки, обращайтесь в нашу техническую поддержку - support@amocrm.ru`

По данному email мне не смогли помочь - говорят там только продажники и к программистам они доступа не имеют и не могут ничем помочь.

Заранее спасибо.
Яна

**Comment by dotzero** [comment]
Спасибо за то, что обратили на это внимание. Видимо они не так давно добавили теги для сделок. Обновите пакет, и можете использовать ваш код, он будет добавлять теги.
```
$lead['tags'] = 'ТЕГ1';
// либо
$lead['tags'] = ['ТЕГ1', 'ТЕГ2'];
```
