### ISSUE TITLE
Постановка времени задачи "Весь день"

### ISSUE THREAD

**Issue by raykl** [dotzero/amocrm-php#20]
Никак не получается поставить задачу на весь день. передавал и "23:59" и текущей датой в timestamp формате, amo выставлял или прошлый месяц или на момент добавления задачи.
Проблема в том что уведомления не приходит в приложение о новой задаче, только за 2 минуты до завершения задачи. Поэтому нужно выставлять на весь день. в моя ошибка? 

    $task = $amo->task;
    $task['element_id'] = $newLead;
    $task['element_type'] = 2;
    $task['task_type'] = 'CALL';
    $task['text'] = "Новая заявка, оставленная с сайта, \nНужно связаться c клиентом";
    $task['responsible_user_id'] = $ResponsUserId;
    $task['complete_till'] = '1491091140';  // сегодняшнее число + 23:59
    $idnewtask = $task->apiAdd();

**Comment by dotzero** [comment]
Попробовал сделать так и задача поставилась на весь день.

```php
ini_set('date.timezone', 'Europe/Moscow');
$task = $amo->task;
$task['element_id'] = 0;
$task['element_type'] = 0;
$task['task_type'] = 1;
$task['text'] = "Текст задачи";
$task['complete_till'] = '23:59:00';
$id = $task->apiAdd();
print_r($id);
```

**Comment by raykl** [comment]
Поменял на свой регион и вправду поставилась на весь день, кто бы знал, что в этом дело. Спасибо!:)

Но тут сразу пока не закрыл тему ещё один вопрос, как уведомить пользователя что ему поставлена задача, клиент использует мобильное приложение, и уведомление приходит только перед закрытием задачи, как реализовать? Или всё таки это некое ограничение и использовать стандартное уведомление на почту о новой сделке?

**Comment by dotzero** [comment]
Видимо никак и только уведомление на почту.

**Comment by raykl** [comment]
Видимо общая проблема у всех популярных crm систем) У битрикса также нет уведомления пользователя при постановки задачи через api.

Спасибо за удобный клиент:)
