### ISSUE TITLE
Мета информация после каждого запроса

### ISSUE THREAD

**Issue by vetheslav** [dotzero/amocrm-php#22]
В случае использования данной библиотеки, как консольное приложение, или как продакшен приложение, очень не хватает возможности взять адекватно информацию об ответе от сервера AmoCrm.
По сути сейчас можно включить сбор дебаг информации, которая будет в любом случае принудительно выводиться на экран, однако для прода это не корректно.
Хорошо будет, если после каждой операции можно будет обратиться к методу, который отдаст предыдущий код ошибки сервера и Body response.

**Comment by dotzero** [comment]
Я сейчас неспешно пишу версию 0.4, которая будет поддерживать ‎PSR-3 логгинг, можно будет подключить какой-нить продвинутый логгер (например `monolog`) и на проде отправлять всю информацию куда нужно.

**Comment by vetheslav** [comment]
Может быть есть смысл временно до 0.4 версии добавить 2 глобальных метода
типа getLastHttpError и getLastHttpResponse?
вт, 23 мая 2017 г. в 16:06, dotzero <notifications@github.com>:

**Comment by dotzero** [comment]
Обновил пакет до 0.3.16, теперь каждая модель содержит методы `getLastHttpCode` и `getLastHttpResponse` 648470e7cf937438320fb06a30e7ff68ad4b0f12
