### ISSUE TITLE
Как добавить примечание?

### ISSUE THREAD

**Issue by Aligan** [dotzero/amocrm-php#24]
при создании сделки как добавить примечание?

**Comment by dotzero** [comment]
Api не позволяет это сделать за один запрос, надо сначала сделать сделку, а вторым запросом добавить примечание примерно как:
```php
$note = $amo->note;
$note['element_id'] =  id_сделки;
$note['element_type'] = 2; // Привязываем к сделке
$note['note_type'] = 4; //  Обычное примечание
$note['text'] = 'Текст примечания';
```
Подробнее о полях:
https://developers.amocrm.ru/rest_api/notes_set.php
https://developers.amocrm.ru/rest_api/notes_type.php

**Comment by Aligan** [comment]
Спасибо

**Comment by Aligan** [comment]
Одна проблема. Почему-то тег < br > не срабатывает, пишет его как текст

**Comment by dotzero** [comment]
Они же не поддерживают теги, пиши через `\n`

**Comment by Aligan** [comment]
Если в самой crm писать, то все поддерживает.

**Comment by dotzero** [comment]
Не могу ответить на этот вопрос, с такими вопросами наверно стоит обратится в поддержку Amo, библиотека никак не преобразовывает отправляемые данные. Если разберетесь, то буду рад обновить библиотеку.
