### ISSUE TITLE
Нет методов для массового обновления

### ISSUE THREAD

**Issue by dmitryvasilevskiy** [dotzero/amocrm-php#30]
Добрый день!
Нет методов для массового обновления для всех сущностей, можно ли добавить?

Заранее спасибо!

**Comment by dotzero** [comment]
Спасибо за проявленный интерес.
Сейчас такой возможности нет. А насколько остро стоит проблема массового обновления? Нужно обновлять больше 5 сделок за раз?

**Comment by dmitryvasilevskiy** [comment]
порой клиенты заносят в номера телефонов лишние символы, приходится периодически чистить...

**Comment by dmitryvasilevskiy** [comment]
```
public function apiUpdateAll($contacts)
    {
        $parameters['contacts']['update'] = $contacts;
        $response = $this->postRequest('/private/api/v2/json/contacts/set', $parameters);
        return isset($response['contacts']) ? true : false;
    }
```
добавил в модель контакты данный метод и работает, правда перед этим получаю $amo->contact->apiList() по 500 шт, и обновляю нужные поля, ибо если не перезаписать все CustomFields можно затереть остальные

**Comment by dotzero** [comment]
Я думал над там чтобы такой функционал включить в версию 0.4, но пока у меня современно не хватает времени на это. В любом случае хорошо бы чтобы из метода возвращался массив где ключи это id изменяемых объектов. И такие методы нужно добавить во все сущности что только добавляет работы. Я всегда рад PullRequest'ам если кто-то возьмется реализовать это.

**Comment by googlogmob** [comment]
@dotzero, тоже возникла необходимость массового обновления кастомных полей. Скажите пожалуйста, в планах добавить эту возможность?
