### ISSUE TITLE
примечание в сделку из неразобранного

### ISSUE THREAD

**Issue by dmitryvasilevskiy** [dotzero/amocrm-php#31]
Добавьте пожалуйста возможность добавлять примечание в сделку из неразобранного, на данный момент можно добавлять только в контакты и пример чуть поправить нужно...

              $note = $amocrm->note;
                $note['element_type'] = 1;
                $note['note_type'] = 4;
                $note['text'] = $value;
                $contact['notes'] = $note;

**Comment by sharovstas** [comment]
У меня кстати вообще примечание не добавляется. Даже для контакта.

**Comment by dotzero** [comment]
Баг с добавлением примечания в сделку поправил. Кроме того неразобранное оказалось слишком большим чтобы хранить все примеры в одном файле. А потому я разнес все примеры использования методов по разным файлам: https://github.com/dotzero/amocrm-php/tree/master/examples/unsorted
Там есть примеры добавления сделок и контактов с примечаниями.
