### ISSUE TITLE
Отсутствует параметр linked_company_id в модели Contact

### ISSUE THREAD

**Issue by user47481** [dotzero/amocrm-php#35]
Возможно я не до конца понимаю специфику линкования, но связать контакт с компанией в сделке без этого параметра нельзя.

**Comment by dotzero** [comment]
Раньше для этого приходилось использовать поле `linked_company_id` в самой сделке, а не в контакте. Но судя по документации они добавили это поле, как обычно, по тихому, нигде об этом не написав.

**Comment by dotzero** [comment]
Спасибо, что обратили внимание, оказалось они успели еще целую кучу полей добавить `created_user_id`, `modified_user_id`, `linked_company_id`. Их я тоже добавил, обновите библиотеку.
