### ISSUE TITLE
Add/Pipeline_id doesn't work

### ISSUE THREAD

**Issue by temposys** [dotzero/amocrm-php#4]
In doc i saw add/pipeline_id https://developers.amocrm.ru/rest_api/leads_set.php
But when i tried - it goes to general pipe anyway. If i do var_dump of object where i set pipeline_id - it's not there.
```
$lead['pipeline_id'] = $config->call_pipeline_id;
var_dump($lead);

["values":protected]=>
  array(4) {
    ["name"]=>
    string(32) "Call from site №495"
    ["status_id"]=>
    int(12110292)
    ["responsible_user_id"]=>
    int(1033413)
    ["tags"]=>
    string(21) "Call, AdSaver"
  }
```
What do i do wrong?

**Comment by dotzero** [comment]
Спасибо за то, что обратили на это внимание. Обновите пакет, и можете использовать ваш код, он будет добавлять теги.

**Comment by temposys** [comment]
Добрый день. Все равно сделки создаются в основной воронке, а не в той, что я указала в pipe_id

**Comment by dotzero** [comment]
Похоже что это баг на стороне amoCrm, попробую им написать. Так как запрос формируется корректный `{"request":{"leads":{"add":[{"pipeline_id":365679,"name":"Test"}]}}}`

**Comment by namig** [comment]
А зачем вообще указывать pipeline_id, достаточно же указать status_id из этой воронки?

**Comment by dotzero** [comment]
Мы на своем проекте именно так и делаем. Но раз уж они добавили такое поле в API, то почему бы не сделать чтоб оно работало.

**Comment by namig** [comment]
Понял, спасибо

**Comment by temposys** [comment]
спасибо большое за подсказку. я даже не знала, что там разные статусы..видимо и пайп не работает потому что надо пайп или статус указывать. а то странно получается если статус я указываю с одной воронки, а хочу создать сделку в другой.

**Comment by dotzero** [comment]
Тех поддержка amoCrm ответила, что без указания `status_id` поле `pipeline_id` работать не будет.

**Comment by namig** [comment]
ну естественно, откуда знать какой статус в воронке поставить

**Comment by temposys** [comment]
Они мне тоже ответили уже. Спасибо.
