### ISSUE TITLE
Ошибка Could not resolve host: .amocrm.ru

### ISSUE THREAD

**Issue by alewkinr** [dotzero/amocrm-php#46]
Добрый день!
Я начинающий, пытаюсь разобраться с Вашей библиотекой. Установил через composer, вроде все работает, но при попытке выполнить тестовый запрос выдает ошибку:
Could not resolve host: .amocrm.ru

Подскажите в чем проблема

**Comment by dotzero** [comment]
При создании клиента `$amo = new \AmoCRM\Client('SUBDOMAIN', 'LOGIN', 'HASH');` Необходимо передать: 

* SUBDOMAIN - Личный поддомен или домен amoCRM
* LOGIN - Логин amoCRM
* HASH - Ключ пользователя amoCRM

**Comment by alewkinr** [comment]
Да, разобрался в чем причина.
Я использовал код для тестирования, который прописан в Вашем репозитории и там параметры SUBDOMAIN, LOGIN, HASH передаются в функцию getenv().
После того, как убрал эту функцию, все заработало.

Можете пояснить в каких случаях эта функция нужна и что она делает, если не трудно

**Comment by dotzero** [comment]
Она читает значения SUBDOMAIN, LOGIN и HASH из системного окружения. Чтобы не хранить все секретные доступы в коде.
