### ISSUE TITLE
Как правильно добавлять кастомное поле для лидов?

### ISSUE THREAD

**Issue by vladimir-shalaev22** [dotzero/amocrm-php#49]
Выполняю что-то вроде `$lead->addCustomField(1965871, 4553623);`
`1965871` - id поля,
`4553623` - id значения.
Обычные поля типа теста и чисел добавляет без проблем.
Но поля где можно выбрать только из нескольких значений не добавляются.
С контактами такой проблемы не было, только с лидами.
Поэтому у меня вопрос, может быть с лидами работа как-то отличается от работы с контактами?

**Comment by dotzero** [comment]
Кастомные поля во всех сущностях добавляются одинаково и зависят только от "типа" кастомного поля:
```php
    // Добавление кастомного поля
    $lead->addCustomField(100, 'Значение');

    // Добавление кастомного поля с типом "мультисписок"
    $lead->addCustomMultiField(200, [
        1237755,
        1237757
    ]);

    // Добавление ENUM кастомного поля
    $lead->addCustomField(300, '+79261112233', 'WORK');

    // Добавление кастомного поля c SUBTYPE поля
    $lead->addCustomField(300, '+79261112233', false, 'subtype');

    // Добавление ENUM кастомного поля с типом "мультисписок"
    $lead->addCustomField(400, [
        ['+79261112233', 'WORK'],
    ]);
```

**Comment by vladimir-shalaev22** [comment]
Нашёл в чем была проблема. Тип поля был мультисписок, а не просто перечисление.
Вместо `$lead->addCustomField(1965871, 4553623);`
сделал `$lead->addCustomField(1965871, [[1, 4553623]]);`
и всё заработало. Долго не мог додуматься до значения `1` для отметки нужного значения
