### ISSUE TITLE
Добавление нового поля существующему контакту.

### ISSUE THREAD

**Issue by raykl** [dotzero/amocrm-php#50]
Пытаюсь обновить существующий контакт, но при изменении самого контакта, старые поля изменяются.
При добавлении email, если есть значение в нём, то добавить новый email отличный от старого не получается, идёт перезапись значения, даже со сменой типа email'а (WORK, OTHER).

**Comment by raykl** [comment]
Вот куски кода:

$find_concact_id_phone= $amo->contact->apiList([
        'query' => $phone,
    ]);
$id_con_phone = $find_concact_id_phone[0][id];
....
$lead = $amo->lead;
$lead['name'] = $subject;
$newLead = $lead->apiAdd();
....
$contact = $amo->contact;
$contact['request_id'] = $id_con_phone;
$contact['linked_leads_id'] = $newLead;
$contact->addCustomField(292783, [
            [$email, 'OTHER'],
        ]);
$contact->apiUpdate((int)$id_con_phone, 'now');

**Comment by raykl** [comment]
С добавлением сделки в контакты разобрался 👍 Но вот с добавлением доп. полей в контакт по типу email и телефона, всё ещё беда. Идёт перезапись, можно ли добавлять в стандартные поля без указания id этого поля?

**Comment by dotzero** [comment]
Если кастомные поля с **множественном** выбором, то всегда будет перезапись, надо сначала получить старые значения, а потом сформировать новое значение котором будет содержать и старое и новое значение. Это особенности работы с API , тут я ничего не могу сделать.

**Comment by raykl** [comment]
Я сейчас так и делаю) думал есть более изящное решение, чем подобные конструкции: 
$find_concact_id_phone= $amo->contact->apiList([
        'query' => $phone,
    ]);
$id_con_email_have = $find_concact_id_phone[0][custom_fields][1][values][0][value];
$id_con_email_have1 = $find_concact_id_phone[0][custom_fields][1][values][1][value];

Другого не придумал, только каждое значение записывать из массива, при перезаписи контакта приходится указывать и id поля, и к какому типу относиться ("рабочий", "другой").

**Comment by dotzero** [comment]
К сожалению API у amoCRM очень убогий в плане получения существующей информации, там где мне надо было сделать что-то подобное я поступал также.
