### ISSUE TITLE
Поиск задач по времени выполнения

### ISSUE THREAD

**Issue by E6yH** [dotzero/amocrm-php#51]
Доброго времени суток. Вкратце надо назначить определенного ответственного на все задачи у которых дата выполнения стоит на сегодня. Автоматом задачи создаются на ответственного по сделке, но в день выполнения задачи может работать другой менеджер и именно .
Как правильно найти назначенные задачи на сегодняшний день для всех пользователей. 
Я так понимаю что $amo->note->apiList([ ... ], 'TODAY')); вернёт под дате создания задачи, или всё же по дате выполнения задачи? Как правильно передать значения диапазона complete_till, или все же надо самому фильтровать задачи?

**Comment by dotzero** [comment]
Все что можно сделать описано тут https://developers.amocrm.ru/rest_api/tasks_list.php и больше никакой фильтрации они не предоставляют. Так что придется брать весь список и уже на своей стороне фильтровать.
