### ISSUE TITLE
неразборное

### ISSUE THREAD

**Issue by alekslv** [dotzero/amocrm-php#52]
Добрый .
как правильно добавить заявку в неразборное,
приэтом данные которые водятся в форму на сайте(телефон например)
при утверждении этой заявки(то есть при переносе например в первичный контакт)
должы подгружаться в соответствующее поле лида

**Comment by dotzero** [comment]
Посмотрите официальную доку: https://developers.amocrm.ru/rest_api/unsorted/add.php
И этот пример https://github.com/dotzero/amocrm-php/blob/master/examples/unsorted/form_to_lead.php

Если кратко, то надо будет самому распарсить данные формы и вставить в соотвествующие кастом поля поля, например.

```php
    // Сделка которая будет создана после одобрения заявки.
    $lead = $amo->lead;
    $lead['name'] = 'New lead from this form';
    $lead->addCustomField(167381, [
        [388743, '6 месяцев'],
    ]);
    $lead->addCustomField(167411, 'Спецпроект');

    // Присоединение сделки к неразобранному
    $unsorted->addDataLead($lead);
    // Добавление неразобранной заявки с типом FORMS
    $unsortedId = $unsorted->apiAddForms();
```
