### ISSUE TITLE
Неразобранное, теги и тело письма

### ISSUE THREAD

**Issue by xnscripter** [dotzero/amocrm-php#54]
// Добавление неразобранной заявки с примечанием из Письма
// include_once __DIR__ . '/unsorted/email_to_lead.php';

1. Теги не добавляются к сделке после одобрения
2. Как добавить текст сообщения, вместо высвечивающегося "Упс! Что-то пошло не так."
3. Какие данные можно не передавать (message_id)?

Возможно AmoCRM обновила методы API?

**Comment by shift-reality** [comment]
ХЗ че они там обновили, но апидок они убили(ссылки кривые)

**Comment by xnscripter** [comment]
Я вчера им звонил, девочка на том конце сказала, 
что вместо ресурса - developers.amocrm.ru/rest_api/
теперь это говно будет - amocrm.ru/developers/

**Comment by dotzero** [comment]
Я думал, что хуже эту документацию уже не сделать.

**Comment by dotzero** [comment]
> Теги не добавляются к сделке после одобрения
> Как добавить текст сообщения, вместо высвечивающегося "Упс! Что-то пошло не так."
> Какие данные можно не передавать (message_id)?

Эти вопросы лучше задать в amo, так как они обо всем этом умалчивают в своей документации, а на проверку всех гипотез у меня сейчас нет не сил не времени.

**Comment by shift-reality** [comment]
а тут никто случайно чаты не делал в амо црм? Почему-то не передается номер телефона в их стандартном примере... хз почему
