### ISSUE TITLE
Удаление сделок и задач

### ISSUE THREAD

**Issue by E6yH** [dotzero/amocrm-php#57]
Не нашёл как удалить сделку. Нашёл только удаление каталогов, полей и т.д. Не понимаю как удалить сделку, или там как-то хитро надо это сделать? Просто знакомой подрубил сервис yclient к амке и он создаёт очень много сделок которые вообще там не нужны. Отсюда и нужда удалять эти сделки как только они создаются.

**Comment by alewkinr** [comment]
Сделки по API удалять нельзя, нет такого метода и не будет. Это против политики компании.
Попробуйте либо отладить интеграцию с Yclients, либо использовать другой сервис. Возможно подойдет Клиентикс
