### ISSUE TITLE
Не актуальные ссылки на документацию

### ISSUE THREAD

**Issue by bigperson** [dotzero/amocrm-php#58]
В Readme.md ссылки на документацию устарели
https://www.amocrm.ru/developers/content/api

**Comment by dmitry4m** [comment]
@bigperson устарели не ссылки, а изменилась версия API и амосрм оставив старую версию API удалила старую документацию.

смотрите документацию на API v2 здесь:
https://web.archive.org/web/20170801033744/https://developers.amocrm.ru/rest_api/

**Comment by dotzero** [comment]
Добавил сопроводительный текст в README
