### ISSUE TITLE
Теряю примечания при пакетном приёме из Неразобранного

### ISSUE THREAD

**Issue by glebkema** [dotzero/amocrm-php#63]
Создаю в &laquo;Неразобранном&raquo; сделки с&nbsp;примечанием. Код писал [на&nbsp;основе примера](https://github.com/dotzero/amocrm-php/blob/master/examples/unsorted/form_to_lead.php):

    // Сделка появится после одобрения заявки
    $lead = $amo->lead;
    $lead['name'] = $lead_name;
    $lead['tags'] = $tags;

    // Примечание появится после одобрения заявки
    $note = $amo->note;
    $note['element_type'] = \AmoCRM\Models\Note::TYPE_LEAD;
    $note['note_type']    = \AmoCRM\Models\Note::COMMON;
    $note['text']         = $note_text;

    $lead['notes'] = $note;

Если принимать заявки из&nbsp;&laquo;Неразобранного&raquo; по&nbsp;одной, то&nbsp;примечания создаются у&nbsp;всех. А&nbsp;если выделить все заявки и&nbsp;принять их &laquo;пакетом&raquo;, то&nbsp;примечание добавляется только к&nbsp;последней.

![-](https://user-images.githubusercontent.com/3881568/36773733-247d7fc6-1c6c-11e8-8c6c-6221803b3af0.png)
![-](https://user-images.githubusercontent.com/3881568/36773739-2d7395ca-1c6c-11e8-8e83-e05b20233738.png)

**Comment by dotzero** [comment]
Это видимо баг самого AmoCrm, попробуйте написать к ним в поддержку.

**Comment by glebkema** [comment]
Переписываюсь с поддержкой AmoCrm. Напишу, если появится полезная информация.

**Comment by glebkema** [comment]
Поддержка AmoCrm всё подробно расспросила, зафиксировала и отправила в работу. Срок исправления неизвестен - зависит от загруженности, сложности и т.п.
Здесь запрос закрываю.
