### ISSUE TITLE
"Системное примечание" для модели Note

### ISSUE THREAD

**Issue by tkachev-o** [dotzero/amocrm-php#65]
Хочу отправлять системные примечания #64  в новой документации только один новый тип примечаний -  SYSTEM с кодом 25.

https://www.amocrm.ru/developers/content/api/notes

**Comment by dotzero** [comment]
Вам стоит смотреть на документацию расположеную тут https://web.archive.org/web/20150325223249/https://developers.amocrm.ru/rest_api/notes_set.php
Так как эта библиотека еще не работает с новым API
