### ISSUE TITLE
Ограничение по количеству запросов к серверу amoCRM

### ISSUE THREAD

**Issue by zerobig** [dotzero/amocrm-php#74]
https://www.amocrm.ru/developers/content/api/recommendations

>Предусмотрены механизмы ограничения активности работы с API - не более 1 запроса в секунду,

Насколько я понял, в коде это ограничение никак не обрабатывается?

**Comment by dotzero** [comment]
Нет и я не планирую это добавлять.

**Comment by zerobig** [comment]
Спасибо конечно за ответ, но если вас не затруднит... Какие основания такого решения? Меня, за три года работы с amoCRM регулярно банили. Причём, в последние разы виноват был уже не я. ))

**Comment by dotzero** [comment]
Дело в том что с точки зрения библиотеки это сложно сделать правильно. Можно конечно хранить счетчик в Client, но не факт что все используют один и тот же экземпляр этого класса. А потому возможны коллизии. Так что самым правильным решением было бы использование такого ограничения в неком middleware который уже вызывает Client, и этот middleware каждый может реализовать у себя. 

Конечно если кто-то сделает PR с таким решением, которое не будет выглядеть как костыль, то я с радостью его приму.

**Comment by rvkulikov** [comment]
Посткомментарий для @zerobig 
Можно делать проверку на стороне приложения настроив глобальный обработчик ошибок, либо пинг crm по крону раз в n минут. Пример:
```php
try {
    $client->account->getUserByLogin('login@domain.com');
} catch (\Exception $e) {
    switch ($e->getCode()) {
        case 429:
            return "AmoCRM 429 API close-to-block";
        case 401:
            return "AmoCRM 401 API cannot-auth";
        case 403:
            return "AmoCRM 403 API blocked";
        default:
            throw $e;
    }
}
```
И дальше отправлять sms разработчику, автоматически писать тикет в support, чтобы разблокировали и так далее.

Единственное примечание для @dotzero 
Теоретически можно сделать специальное исключение для 403 кода, которое унаследуется от NetworkException, чтобы было BC, но вот нужно ли это - отдельный вопрос.

**Comment by zerobig** [comment]
@rvkulikov, идея была не в том чтобы как-то реагировать на факт блокировки, а предотвратить блокировку выполняя требования сервиса по количеству обращений в секунду. А так, да. Спасибо за ваш комментарий.
