### ISSUE TITLE
Domain name conflict RU with COM on login

### ISSUE THREAD

**Issue by danieltorscho** [dotzero/amocrm-php#76]
В amoCRM если создать аккаунт на английском языке, то концовка доменного имени, которая работает, будет не .ru  а .com...

Можно изменить в файле `/src/Client.php` на линии 71 строку с

    $domain = sprintf('%s.amocrm.ru', $domain);

на 

    $domain = sprintf('%s', $domain);

а в конфиг файле дописать полный адрес домены (example.amocrm.ru)

**Comment by tkachev-o** [comment]
Лучше проверять переданный параметр, если передан в виде адреса с указанием домена верхнего уровня – использовать, чтобы сохранить обратную совместимость.

**Comment by danieltorscho** [comment]
Я извиняюсь, там уже стоит проверка на полный адрес домены.

`if (strpos($domain, '.') === false) {`

если указать полный адрес например `example.amocrm.com` то будет подставлятся этот.
