### ISSUE TITLE
Help wanted!

### ISSUE THREAD

**Issue by andrewalf** [dotzero/amocrm-php#8]
Доброго времени суток.
Не могу понять в чем именно проблема, быть может вы сможете подсказать. Происходит дублирование при создании сущностей.
Например, я создаю контакт. Во включенном debug все верно. Т.е. тело POST запроса корректное.
Запрос отправляется один, это тоже проверял.
Но в amoCRM создается два идентичных контакта. То же самое и с, например, лидами.
Запустил пример из examples, без моих классов - то же самое. Ответ от API такой, будто добавилась одна запись. Например:
```php
["response"]=>
  array(2) {
    ["contacts"]=>
    array(1) {
      ["add"]=>
      array(1) {
        [0]=>
        array(2) {
          ["id"]=>
          int(23327682)
          ["request_id"]=>
          int(0)
        }
      }
    }
    ["server_time"]=>
    int(1484230622)
  }
```

Но если я отправляю такой же запрос, с таким же телом запроса, через Postman, то корректно создается одна запись.

Например, при следующем запросе создаются две записи:
```php
$client = new \AmoWrapper\Client('xxx', 'yyy', 'zzz);
$contact = $client->contact;
$contact->debug(true);
$contact['name'] = 'ФИО';
$contact->apiAdd();
```

**Comment by andrewalf** [comment]
Я скопировал Request::request, захардкодил данные. Результат тот же - создаются 2 записи.
Получается, это что-то с cURL-ом не так?

Ниже привожу код, который я запускал:
```php
$client = new \AmoWrapper\Client('xxx', 'yyy', 'zzz);

$headers = ['Content-Type: application/json'];

$query = http_build_query([
    'USER_LOGIN' => 'yyy',
    'USER_HASH' => 'zzz',
]);

$endpoint = sprintf('https://%s.amocrm.ru%s?%s', 'xxx', '/private/api/v2/json/contacts/set', $query);

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $endpoint);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode([
    'request' => [
        'contacts' => [
            'add' => [
                [
                     'name' => 'тестовое имя',
                ];
            ],
        ],
    ],
]));


$result = curl_exec($ch);
curl_close($ch);

$result = json_decode($result, true);
var_dump($result);
```

**Comment by dotzero** [comment]
А попробуйте запустить тотже пример через консоль, а не через браузер. Может браузер или nginx/apache дублирует запрос?

**Comment by andrewalf** [comment]
Больше спасибо! Такие простые слова заставили меня искать проблему в другом направлении.
И проблемы быстро нашлась. В силу своей неопытности зациклился на коде и искал проблему там.

Браузер всегда отправляет http-Запрос на фавиконку. У меня фавиконки не было. А в настройках хоста редирект всех запросов к несуществующим файлам на index.php.
Итог - скрипт запускается дважды.

Извиняюсь за поднятие темы с такой глупостью.
