### ISSUE TITLE
не могу получить связанный контакт лида

### ISSUE THREAD

**Issue by sergejfreelancer** [dotzero/amocrm-php#88]
По вебхуку прилетает архив. Из него беру id сделки и пытаюсь получить телефон связанного контакта, но в ответ приходит пустота
`$contactInfo = $amo->contact->apiList(['query' => '51191897',]);`
51191897 - это значение 'main_contact_id' => 51191897 из вебхука сделки.

**Comment by shmidtelson** [comment]
> 
> 
> По вебхуку прилетает архив. Из него беру id сделки и пытаюсь получить телефон связанного контакта, но в ответ приходит пустота
> `$contactInfo = $amo->contact->apiList(['query' => '51191897',]);`
> 51191897 - это значение 'main_contact_id' => 51191897 из вебхука сделки.

Здравствуйте! Используйте другой ключ для поиска.

`id | Выбрать элемент с  заданным ID (Если указан этот параметр, все остальные  игнорируются)(Можно передавать в виде массива состоящий из нескольких  ID)`

`$contactInfo = $amo->contact->apiList(['id' => 51191897,]);`

**Comment by coller13** [comment]
> По вебхуку прилетает архив. Из него беру id сделки и пытаюсь получить телефон связанного контакта, но в ответ приходит пустота
> `$contactInfo = $amo->contact->apiList(['query' => '51191897',]);`
> 51191897 - это значение 'main_contact_id' => 51191897 из вебхука сделки.

Зачем использовать поиск, если у вас известен main_contact_id? Проще получить контакт по id

**Comment by sergejfreelancer** [comment]
уже сделал через поиск связей, но теперь вставл вопрос, как сделать контроль дублей именно сделок по имени сделки.

**Comment by sergejfreelancer** [comment]
Проверял по логам скрипта. Всё нормально, но дубли все-равно пропускает. Причем, не все

**Comment by sergejfreelancer** [comment]
>>> Проще получить контакт по id
А как?
