### ISSUE TITLE
Protected field 'date_create', для модели Lead неактуально. Предлагаю заменить на 'created_at'

### ISSUE THREAD

**Issue by atvoretz** [dotzero/amocrm-php#91]
Protected field 'date_create', для модели Lead неактуально. Предлагаю заменить на 'created_at'

**Comment by tkachev-o** [comment]
Неактуально только для новой версии документации, прочитайте Readme там есть ссылка на старую документацию.

**Comment by atvoretz** [comment]
date create не работает. Пробую создавать сделку задним числом

**Comment by atvoretz** [comment]
Разобрался. Благодарю
