### ISSUE TITLE
401 Invalid response body

### ISSUE THREAD

**Issue by tkachev-o** [dotzero/amocrm-php#93]
Со вчерашнего дня вылетает исключение с кодом 401 - Invalid response body, при попытке доставить **неразобранное**. Кто-нибудь наблюдает подобную проблему? Задал вопрос в поддержку.

**Comment by i4j5** [comment]
Такая же проблема

**Comment by i4j5** [comment]
Ждем ответа от amo

**Comment by ov4pek** [comment]
Аналогичная проблема

**Comment by i4j5** [comment]
Заработало
