### ISSUE TITLE
Выбор ответственного в зависимости от выбраного value формы

### ISSUE THREAD

**Issue by aka-87** [dotzero/amocrm-php#95]
Подскажите, как назначить ответственного сделки в зависимости от введенных данных в форме на сайте. 
Пытаюсь так:
`if($city=='Івано-Франківськ'){ // Франковск
            $lead['responsible_user_id'] = 2523706;
        }elseif($city=='Рівне'){ // Ровно
            $lead['responsible_user_id'] = 2523715;
        }elseif($city=='Житомир'){ // Житомир
            $lead['responsible_user_id'] = 2523694;
        }elseif($city=='Хмельницький'){ // Хмельницкий
            $lead['responsible_user_id'] = 2523700;
        }elseif($city=='Чернівці'){ // Черновцы
            $lead['responsible_user_id'] = 2523703;
        }elseif($city=='Полтава'){ // Полтава
            $lead['responsible_user_id'] = 2523703;
        }elseif($city=='Тернопіль'){
            $lead['responsible_user_id'] = 2523712;
        }elseif($city=='Суми'){ // Суми
            $lead['responsible_user_id'] = 2523712;
        };`
но это не работает.
В поддержке ответили: 

> это сторонняя библиотека и в ней используются устаревшие методы. Не могу вас проконсультировать по ее использованию. Мы рекомендуем использовать актуальные методы, описанные в нашей документации

**Comment by tkachev-o** [comment]
Попробуйте временно исключить эти конструкции if else.

Установите любое значение, к примеру так:
$lead['responsible_user_id'] = 2523706;

**Comment by aka-87** [comment]
Сработало, но как сделать зависимость от выбранного города?

**Comment by tkachev-o** [comment]
Теперь осталось убедиться в том, что в переменной $city перед вашими конструкциями if else присутствует значение, которое вы хотите обработать.

**Comment by aka-87** [comment]
а как это проверить?

**Comment by aka-87** [comment]
вообще, это кастомная форма:
`$lead->addCustomField(636487, [
            [$_POST['city']],
        ]);`

**Comment by aka-87** [comment]
` custom_fields: [

    {
        id: 636487,
        name: "Мiсто",
        values: [
            {
                value: "Чернівці",
                enum: 1169121
            }
        ],
        is_system: false
    }

],`

**Comment by aka-87** [comment]
наверное я неправильно составляю конструкцию?

**Comment by tkachev-o** [comment]
Ну скорее всего я бы отказался от нее, хотя бы так для начала:

        
```
// Default
$responsibleUserId = 2523706;

switch ($city){
    case 'Івано-Франківськ':
      $responsibleUserId = 2523706;
      break;
    case 'Рівне':
      $responsibleUserId= 2523706;
      break;
    default:
      $responsibleUserId= 19468561;
}

$amo = new \AmoCRM\Client(getenv('DOMAIN'), getenv('LOGIN'), getenv('HASH'));
...
$lead['responsible_user_id'] = $responsibleUserId;

```

**Comment by aka-87** [comment]
сейчас попробую, спасибо!

**Comment by aka-87** [comment]
ответственный всё равно не меняется

**Comment by aka-87** [comment]
Мне кажется нужно проверять не $city а custom_fields , но как это сделать правильно я не знаю

**Comment by aka-87** [comment]
проблема решена, проверять нужно было не $city а $_POST['city']
