### ISSUE TITLE
Как получить сделку или контакт по id?

### ISSUE THREAD

**Issue by EgoRoman** [dotzero/amocrm-php#98]
`$leads = $searchContact[0]['linked_leads_id']);`
`foreach ($leads as $leadId) {`
`        $lead = $amo->contact->apiList([`
`          'id' => $leadId,`
`        ]);`
`        print_r($lead);`
`}`
Пробую так, но возвращает все сделки, как-будто поле id не работает в запросе.

UPD:
$lead = $amo->contact->apiList([
'id' => 13519165,
]);
Не работает.

**Comment by tkachev-o** [comment]
Вы пытаетесь в цикле получить сделки, а метод используете для запроса контакта. 

Также сделайте один запрос - передав массив id сделок.

Лучше всего включите режим отладки debug = true

**Comment by EgoRoman** [comment]
> Вы пытаетесь в цикле получить сделки, а метод используете для запроса контакта.
> 
> Также сделайте один запрос - передав массив id сделок.

Да даже так пробую:
$lead = $amo->contact->apiList([
        'id' => 13519165,
      ]);
      print_r($lead);
Ничего не выводит.
Выводится пустой массив, хотя сделка с таким id (13519165) есть.
Вместо id использовать query не вариант, вдруг id совпадет с цифрами в телефоне.

**Comment by tkachev-o** [comment]
$ids = $amo->lead->apiAdd([$lead1, $lead2]);
    print_r($ids);

Пользуйтесь документацией

**Comment by tkachev-o** [comment]
print_r($amo->lead->apiList([
        'query' => 13519165,
    ]));

**Comment by EgoRoman** [comment]
так в документации и было написано:

id | Выбрать элемент с заданным ID (Если указан этот параметр, все остальные игнорируются)(Можно передавать в виде массива состоящий из нескольких ID)
-- | --

**Comment by EgoRoman** [comment]
> $ids = $amo->lead->apiAdd([$lead1, $lead2]);
> print_r($ids);
> 
> Пользуйтесь документацией

Зачем добавление сделки?

**Comment by tkachev-o** [comment]
В шапке данного репозитория сказано, что ребята из Amo обновили Api, но старая версия с которой взаимодействует данная библиотека еще пока поддерживается.

**Comment by EgoRoman** [comment]
> print_r($amo->lead->apiList([
> 'query' => 13519165,
> ]));

Использовать query не вариант, вдруг id совпадет с цифрами в телефоне контакта.

**Comment by EgoRoman** [comment]
> так в документации и было написано:
> 
> id	Выбрать элемент с заданным ID (Если указан этот параметр, все остальные игнорируются)(Можно передавать в виде массива состоящий из нескольких ID)

Это как раз из старой док-ии 
https://web.archive.org/web/20140903201224/https://developers.amocrm.ru/rest_api/leads_list.php

**Comment by tkachev-o** [comment]
print_r($amo->lead->apiList([
'query' => 13519165,
]));

Замените query на id

**Comment by EgoRoman** [comment]
> print_r($amo->lead->apiList([
> 'query' => 13519165,
> ]));
> 
> Замените query на id

ты бот?

**Comment by EgoRoman** [comment]
> $lead = $amo->contact->apiList([
> 'id' => 13519165,
> ]);
> print_r($lead);
> Ничего не выводит.
